 dbt_pipeline_demo:
  outputs:
    dev:
      type: duckdb
      path: databases/dbt_pipeline_demo.duckdb
      extensions:
        - parquet
        - s3
        - json
      threads: 1
    prod:
      type: duckdb
      path: databases/prod.duckdb
      threads: 4
  target: dev