[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Project Data Pipeline—Demo"
version = "4.0.0"
description = "A complete, end to end data pipeline demonstration for processing of generated product data."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name="Bruce Anthony Lee", email="brucelee352@gmail.com" }
]
license = { file="LICENSE" }

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Data Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis"
]
dependencies = [
    "duckdb>=0.8.1",
    "minio>=7.1.0",
    "pandas>=2.0.0",
    "faker>=18.0.0",
    "dbt-core>=1.5.0",
    "dbt-duckdb>=1.5.0",
    "python-dotenv>=1.0.0",
    "user-agents>=2.2.0"
]

[project.optional-dependencies]
dev = [
    "black>=23.0.0",
    "flake8>=6.0.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "mypy>=1.0.0"
]
docs = [
    "mkdocs>=1.4.0",
    "mkdocs-material>=9.0.0",
    "dbt-docs>=0.14.0"
]

[project.scripts]
run-pipeline = "scripts.main_data_pipeline:main"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true 